import { WxIsv } from '../typings'

export const AuthScopes: WxIsv.Dic<WxIsv.WxIsvAuthItem> = {
  17: {
    id: 17,
    name: '帐号管理权限',
    alias: 'account',
    desc: '帮助小程序获取二维码，进行帐号管理',
    mutex: false,
    required: true,
  },
  18: {
    id: 18,
    name: '开发管理与数据分析权限',
    alias: 'developAndAnalysis',
    desc: '帮助小程序进行功能开发与数据分析',
    mutex: true,
    required: true,
  },
  19: {
    id: 19,
    name: '客服消息管理权限',
    alias: 'customerService',
    desc: '帮助小程序接收和发送客服消息',
    mutex: false,
  },
  25: {
    id: 25,
    name: '开放平台帐号管理权限',
    alias: 'openAccount',
    desc: '帮助小程序绑定开放平台帐号，实现用户身份打通',
    mutex: true,
    required: true,
  },
  30: {
    id: 30,
    name: '小程序基本信息设置权限',
    alias: 'basicInfo',
    desc: '帮助小程序设置名称、头像、简介、类目等基本信息',
    mutex: false,
    required: true,
  },
  31: {
    id: 31,
    name: '小程序认证权限',
    alias: 'wxVerify',
    desc: '帮助小程序申请认证',
    mutex: false,
    required: true,
  },
  36: {
    id: 36,
    name: '微信卡路里权限',
    alias: 'calories',
    desc: '为小程序提供用户卡路里同步、授权查询、兑换功能',
    mutex: false,
  },
  37: {
    id: 37,
    name: '附近地点权限',
    alias: 'nearbyPoi',
    desc: '帮助小程序创建附近地点，可设置小程序展示在“附近的小程序”入口中',
    mutex: false,
  },
  40: {
    id: 40,
    name: '插件管理权限',
    alias: 'plugins',
    desc: '用于代小程序管理插件的添加和使用',
    mutex: true,
    required: true,
  },
  41: {
    id: 41,
    name: '好物圈权限',
    alias: 'goodSphere',
    desc: '帮助小程序将物品、订单、收藏等信息同步至好物圈，方便用户进行推荐',
    mutex: true,
  },
  45: {
    id: 45,
    name: '快递配送权限',
    alias: 'logistics',
    desc: '帮助有快递配送需求的开发者，快速高效对接多家快递公司。对接后用户可通过微信服务通知接收实时快递配送状态，提升用户体验',
    mutex: true,
  },
  48: {
    id: 48,
    name: '微信财政电子票据权限',
    alias: 'electronicTicket',
    desc: '帮助小程序完成授权、插卡及报销',
    mutex: false,
  },
  49: {
    id: 49,
    name: '云开发管理权限',
    alias: 'cloudDevelopment',
    desc: '帮助小程序管理小程序·云开发资源',
    mutex: true,
  },
  51: {
    id: 51,
    name: '即时配送权限',
    alias: 'immediateDelivery',
    desc: '旨在解决餐饮、生鲜、超市等小程序的外卖配送需求，接入后小程序商家可通过统一的接口获得多家配送公司的配送服务，提高经营效率',
    mutex: true,
  },
  52: {
    id: 52,
    name: '小程序直播权限',
    alias: 'broadcast',
    desc: '帮助有直播需求的小程序实现在小程序上直播边看边买的能力',
    mutex: false,
  },
  57: {
    id: 57,
    name: '页面推送权限',
    alias: 'submitPages',
    desc: '帮助小程序推送小程序页面给搜索引擎，增加小程序页面在搜索的收录与曝光机会',
    mutex: false,
  },
  65: {
    id: 65,
    name: '广告管理权限',
    alias: 'advertising',
    desc: '帮助广告主进行微信广告的投放和管理',
    mutex: false,
  },
  67: {
    id: 67,
    name: '服务平台管理权限',
    alias: 'serviceMarket',
    desc: '帮助小程序管理服务平台上购买的资源',
    mutex: false,
  },
  70: {
    id: 70,
    name: '商品管理权限',
    alias: 'merchant',
    desc: '支持对小商店商品及库存信息进行管理',
    mutex: false,
  },
  71: {
    id: 71,
    name: '订单与物流管理权限',
    alias: 'orderAndLogistics',
    desc: '支持对小商店订单及物流信息进行管理',
    mutex: false,
  },
  76:{
    id: 76,
    name: '小程序违规与交易投诉管理权限',
    alias: 'complain',
    desc: '支持对小程序违规与交易投诉进行管理',
    mutex: true,
  }
  ,
  88:{
    id: 88,
    name: '小程序链接管理',
    alias: 'url',
    desc: '基于该权限可获取小程序链接',
    mutex: false,
  }
}

export const MpAuthScopes: WxIsv.Dic<WxIsv.WxIsvAuthItem> = {
  1: {
    id: 1,
    name: '消息管理权限',
    alias: 'message',
    desc: '帮助公众号接收用户消息，进行人工客服回复或自动回复',
    mutex: false,
    required: true,
  },
  2: {
    id: 2,
    name: '用户管理权限',
    alias: 'user',
    desc: '帮助公众号获取用户基本信息，进行用户分组管理',
    mutex: false,
    required: true,
  },
  3: {
    id: 3,
    name: '账号服务权限',
    alias: 'account',
    desc: '帮助公众号设置及展示公众号信息、配置账号信息、生成带参二维码并配置跳转小程序等账号维度的功能',
    mutex: false,
    required: true,
  },
  4: {
    id: 4,
    name: '网页服务权限',
    alias: 'web',
    desc: '帮助公众实现H5网页服务',
    mutex: false,
  },
  5: {
    id: 5,
    name: '微信小店权限',
    alias: 'store',
    desc: '帮助公众号使用微信小店功能',
    mutex: false,
  },
  6: {
    id: 6,
    name: '微信多客服权限',
    alias: 'kf',
    desc: '帮助公众号使用微信多客服功能',
    mutex: false,
  },
  7: {
    id: 7,
    name: '群发与通知权限',
    alias: 'sendingAndNotification',
    desc: '帮助公众号进行群发消息、文章管理、发送模板消息',
    mutex: false,
    required: true,
  },
  8: {
    id: 8,
    name: '微信卡券权限',
    alias: 'card',
    desc: '帮助公众号使用微信卡券功能',
    mutex: false,
  },
  9: {
    id: 9,
    name: '微信扫一扫权限',
    alias: 'sweep',
    desc: '帮助公众号使用微信扫一扫功能',
    mutex: false,
  },
  10: {
    id: 10,
    name: '微信连WIFI权限',
    alias: 'wifi',
    desc: '帮助公众号使用微信连WIFI功能',
    mutex: false,
  },
  11: {
    id: 11,
    name: '素材管理权限',
    alias: 'media',
    desc: '帮助公众号管理图文等多媒体素材以及多媒体文件管理',
    mutex: false,
    required: true,
  },
  12: {
    id: 12,
    name: '微信摇周边权限',
    alias: 'neighbor',
    desc: '帮助公众号使用微信摇周边功能',
    mutex: false,
  },
  13: {
    id: 13,
    name: '微信门店权限',
    alias: 'poi',
    desc: '帮助公众号使用微信门店功能',
    mutex: false,
  },
  15: {
    id: 15,
    name: '菜单管理权限',
    alias: 'menu',
    desc: '帮助公众号使用自定义菜单功能进行菜单管理',
    mutex: false,
    required: true,
  },
  22: {
    id: 22,
    name: '城市服务权限',
    alias: 'cityService',
    desc: '帮助公众号使用微信城市服务功能',
    mutex: false,
  },
  23: {
    id: 23,
    name: '广告管理权限',
    alias: 'advertising',
    desc: '帮助公众号广告主进行微信广告的投放和管理',
    mutex: false,
  },
  24: {
    id: 24,
    name: '开放平台账号管理权限',
    alias: 'openAccount',
    desc: '帮助公众号实现绑定开放平台账号功能',
    mutex: true,
    required: true,
  },
  26: {
    id: 26,
    name: '微信电子发票权限',
    alias: 'invoice',
    desc: '帮助公众号使用微信电子发票功能',
    mutex: false,
  },
  27: {
    id: 27,
    name: '快速注册小程序权限',
    alias: 'registerMiniprogram',
    desc: '帮助公众号实现复用公众号资质快速注册小程序功能',
    mutex: false,
  },
  33: {
    id: 33,
    name: '小程序关联管理权限',
    alias: 'linkMiniprogram',
    desc: '实现将小程序关联/解除关联公众号',
    mutex: false,
    required: true,
  },
  34: {
    id: 34,
    name: '微信商品库管理权限',
    alias: 'product',
    desc: '帮助公众号商家导入、更新、查询微信商品库的商品信息',
    mutex: true,
  },
  35: {
    id: 35,
    name: '微信卡路里权限',
    alias: 'calorie',
    desc: '帮助公众号提供用户卡路里同步、授权查询、兑换等功能',
    mutex: false,
  },
  44: {
    id: 44,
    name: '好物圈权限',
    alias: 'hwq',
    desc: '帮助公众号将物品、订单、收藏等信息同步至好物圈',
    mutex: false,
  },
  46: {
    id: 46,
    name: '微信一物一码权限',
    alias: 'mark',
    desc: '帮助公众号使用微信一物一码功能',
    mutex: false,
  },
  47: {
    id: 47,
    name: '微信财政电子票据权限',
    alias: 'ticket',
    desc: '帮助公众号完成授权、插卡及报销等功能',
    mutex: false,
  },
  54: {
    id: 54,
    name: '服务号对话管理权限',
    alias: 'dialogue',
    desc: '帮助公众号配置对话能力，管理顾问、客户、标签和素材等功能',
    mutex: true,
  },
  66: {
    id: 66,
    name: '微信服务市场管理权限',
    alias: 'serviceMarket',
    desc: '代公众号调用在微信服务市场购买的API资源',
    mutex: false,
  },
  89: {
    id: 89,
    name: '服务号订阅通知权限',
    alias: 'subscriptionNotification',
    desc: '帮助服务号使用订阅通知',
    mutex: false,
    required: true,
  },
  121: {
    id: 121,
    name: '公众号购物订单权限',
    alias: 'order',
    desc: '实现在微信内上传公众号中的用户购物详情信息，包括上传购物详情信息、上传物流信息、提交平台审核等',
    mutex: false,
  },
}
